// <auto-generated />
namespace SACAAE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes26Ago : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes26Ago));
        
        string IMigrationMetadata.Id
        {
            get { return "201508262323443_changes26Ago"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
