// <auto-generated />
namespace SACAAE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sedefix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sedefix));
        
        string IMigrationMetadata.Id
        {
            get { return "201508290623285_sede-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
